version: "3"
services:
  db:
    image: postgres
    ports:
      - '5432:5432' # ホストからゲストへポートフォワード
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile    
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true # コンテナを起動させ続ける
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
  volumes:
    postgresql-data:
      driver: local